### ISSUE TITLE
Information Architecture

### ISSUE THREAD

**Issue by Unique-Gift** [zuri-training/T-C-PP_gen_pjt73#2]
Annette Shadeya
Eze Michael
Oladapo Itunuoluwa 
Judith Joe

**Comment by AnnieUXUI** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=303%3A315

**Comment by chi-joe** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=0%3A1

**Comment by Michael-Kings** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=1298%3A2823

**Comment by Ditoruncaus** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=303%3A315
