### ISSUE TITLE
Presentation slide

### ISSUE THREAD

**Issue by Unique-Gift** [zuri-training/T-C-PP_gen_pjt73#4]

**Comment by AnnieUXUI** [comment]
https://www.figma.com/proto/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=617%3A1314&scaling=contain&page-id=326%3A875

**Comment by AnnieUXUI** [comment]
[https://www.figma.com/proto/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=617%3A1314&scaling=contain&page-id=326%3A875](url)

**Comment by AnnieUXUI** [comment]
https://www.figma.com/proto/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=617%3A1314&scaling=contain&page-id=326%3A875
