### ISSUE TITLE
Style guides

### ISSUE THREAD

**Issue by Unique-Gift** [zuri-training/T-C-PP_gen_pjt73#5]
Unique-Gift Amah
Samuel Mong
Victor Onyema 
Abasiama Okon

**Comment by kingoftwins** [comment]
Done https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=66%3A2

**Comment by Unique-Gift** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=66%3A2
