### ISSUE TITLE
Competitive audit

### ISSUE THREAD

**Issue by Unique-Gift** [zuri-training/T-C-PP_gen_pjt73#8]
Ogechi Marry Eze 
Annette shadeya

**Comment by Ogeeze** [comment]
https://docs.google.com/document/d/1aIDYF0fvOzZ6IzfFL8tM6YDwpmEXACp_UX2wx7-kmRM/edit?usp=drivesdk

**Comment by AnnieUXUI** [comment]
[https://docs.google.com/document/d/1aIDYF0fvOzZ6IzfFL8tM6YDwpmEXACp_UX2wx7-kmRM/edit?usp=sharing](url)

**Comment by AnnieUXUI** [comment]
https://docs.google.com/document/d/1aIDYF0fvOzZ6IzfFL8tM6YDwpmEXACp_UX2wx7-kmRM/edit?usp=sharing
