### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by Unique-Gift** [zuri-training/T-C-PP_gen_pjt73#9]
Eze michael
Esther Adekunle

**Comment by estheradeks** [comment]
User Story. (Done)
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=1270%3A2738

**Comment by Michael-Kings** [comment]
https://www.figma.com/file/S3LMt4vY5ivPCBDdfBK1Gq/Team-73-%2F-proj-t_c_gen?node-id=1298%3A4013
User Story Done.
